[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "cyfrin-aave/=lib/defi-aave-v3/foundry/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "${FORK_URL}"